OhInstagramBundle_callback:
    path: /instaphp/callback
    defaults: { _controller: OhInstagramBundle:Instagram:callback }
    
OhInstagramBundle_logout:
    path: /logout
    defaults: { _controller: OhInstagramBundle:Instagram:logout }
    
OhInstagramBundle_ajax_location_search:
    path: /ajax/locationSearch
    defaults: { _controller: OhInstagramBundle:Instagram:locationSearch, _format: json }

OhInstagramBundle_ajax_follow:
    path: /ajax/follow
    defaults: { _controller: OhInstagramBundle:Instagram:follow, _format: json }

OhInstagramBundle_ajax_like:
    path: /ajax/like
    defaults: { _controller: OhInstagramBundle:Instagram:like, _format: json }

OhInstagramBundle_ajax_comment:
    path: /ajax/comment
    defaults: { _controller: OhInstagramBundle:Instagram:comment, _format: json }
